// Auto-generated inclusion file
#pragma once
#include "pipeline/vk-compute-pipeline-factory.hpp"
#include "pipeline/vk-graphics-pipeline-factory.hpp"
#include "pipeline/vk-pipeline-color-blend-attachment-state.hpp"
#include "pipeline/vk-pipeline-color-blend-state.hpp"
#include "pipeline/vk-pipeline-depth-stencil-state.hpp"
#include "pipeline/vk-pipeline-dynamic-state.hpp"
#include "pipeline/vk-pipeline-input-assembly-state.hpp"
#include "pipeline/vk-pipeline-input-vertex-state.hpp"
#include "pipeline/vk-pipeline-layout.hpp"
#include "pipeline/vk-pipeline-multisampling-state.hpp"
#include "pipeline/vk-pipeline-rasterization-state.hpp"
#include "pipeline/vk-pipeline-shader-stage.hpp"
#include "pipeline/vk-pipeline-shader-stages.hpp"
#include "pipeline/vk-pipeline-vertex-array-binding.hpp"
#include "pipeline/vk-pipeline-viewport-state.hpp"
#include "pipeline/vk-pipeline.hpp"
